# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'BoardGameList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoardGameList
  pod 'R.swift'
  pod 'Sourcery'
  pod 'SwiftLint'
    
  target 'BoardGameListTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
